services:
  api:
    build: .
    container_name: meetlify_api

    env_file:
      - .env

    ports:
      - "8000:8000"

    command: uvicorn main:app --host 0.0.0.0 --port 8000
  # worker:
  #   build: .
  #   container_name: meetlify_worker
  #   volumes:
  #     - ./app:/app
  #   env_file:
  #     - .env
  #   command: celery -A core.celery_app.celery_app worker --pool=solo --loglevel=info

  # beat:
  #   build: .
  #   container_name: meetlify_beat
  #   volumes:
  #     - ./app:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - worker
  #   command: celery -A core.celery_app.celery_app beat --loglevel=info

