"""Add Thumbnail Public id Column

Revision ID: 4685128fdf6e
Revises: c39244acb907
Create Date: 2026-06-12 13:50:07.677059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4685128fdf6e'
down_revision: Union[str, Sequence[str], None] = 'c39244acb907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('thumbnail_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'thumbnail_public_id')
    # ### end Alembic commands ###
