"""add cascade delete to registrations

Revision ID: 4a5a612e601e
Revises: b16db8755c2c
Create Date: 2026-06-25 15:07:41.485221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5a612e601e'
down_revision: Union[str, Sequence[str], None] = 'b16db8755c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('registrations_event_id_fkey'), 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.create_foreign_key(op.f('registrations_event_id_fkey'), 'registrations', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
