"""Thumnail and video url column is added in Event Model

Revision ID: c39244acb907
Revises: ad041d758f7c
Create Date: 2026-06-12 12:15:33.490605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39244acb907'
down_revision: Union[str, Sequence[str], None] = 'ad041d758f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'video_url')
    op.drop_column('events', 'thumbnail_url')
    # ### end Alembic commands ###
