"""Updated

Revision ID: cef6d5df4b17
Revises: 684267f521e8
Create Date: 2026-06-13 18:37:06.787202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef6d5df4b17'
down_revision: Union[str, Sequence[str], None] = '684267f521e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'max_seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('max_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
