"""Add new column in registration

Revision ID: d974dd092d30
Revises: d2fdd3246953
Create Date: 2026-06-22 11:25:02.794921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd974dd092d30'
down_revision: Union[str, Sequence[str], None] = 'd2fdd3246953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('reminder_sent', sa.Boolean(), server_default=sa.false(),nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'reminder_sent')
    # ### end Alembic commands ###
